# Overview
I think the `load_config` function in astera is a good sample function for Dylan...there are a few variables,
and some with nested structures (which is the key test case to make sure we have "dependencies" defined first)

In [1]:
!ls ~/exp_builds/astera.exp/rundata/run1/0.fighter
# !ls ~/exp_builds/astera.exp

0.fighter	   function_params.csv	      locals.stats.csv
0.fighter.debug    function_params.stats.csv  _raw_debug_locals.csv
ast_dumps	   functions.csv	      _raw_dwarf_locals.csv
fighter		   ghidra_ast.debug.json      _raw_stripped_locals.csv
fighter.debug	   ghidra_ast.json
fighter.dwarf.sdb  locals.csv

In [2]:
from pathlib import Path
import pandas as pd

bin_folder = Path.home()/'exp_builds/astera.exp/rundata/run1/0.fighter'

funcs_df = pd.read_csv(bin_folder/'functions.csv')
locals_df = pd.read_csv(bin_folder/'locals.csv')

raw_debug = pd.read_csv(bin_folder/'_raw_debug_locals.csv')
raw_dwarf = pd.read_csv(bin_folder/'_raw_dwarf_locals.csv')
raw_strip = pd.read_csv(bin_folder/'_raw_stripped_locals.csv')

In [3]:
addr = funcs_df[funcs_df.FunctionName_Debug=='init_game'].FunctionStart.iloc[0]
locals_df[locals_df.FunctionStart==addr]

,FunctionStart,Signature,Name_Strip,Type_Strip,LocType_Strip,LocRegName_Strip,LocOffset_Strip,TypeCategory_Strip,TypeSeq_Strip,Name_Debug,Type_Debug,LocType_Debug,LocRegName_Debug,LocOffset_Debug,TypeCategory_Debug,TypeSeq_Debug,HasDWARF,LeafSID,BinaryId
373,1351728,"400,408,408,408",lVar1,int64,register,rcx,8,BUILTIN,int64,lVar3,int64,register,rcx,8.0,BUILTIN,int64,False,-1,0
374,1351728,"405,408,408,408",puVar2,uint64*,register,rdi,56,POINTER,"PTR,uint64",ppVar4,player_t*,register,rdi,56.0,POINTER,"PTR,STRUCT",False,58,0
375,1351728,"4,408",bVar3,uchar,register,df,522,BUILTIN,uchar,bVar5,uchar,register,df,522.0,BUILTIN,uchar,False,-1,0
376,1351728,"271,281",fVar4,float,register,xmm1_da,4640,BUILTIN,float,fVar6,float,register,xmm1_da,4640.0,BUILTIN,float,False,-1,0
377,1351728,"0,144",uVar5,uint32,register,xmm1_db,4644,BUILTIN,uint32,NaN,NaN,NaN,NaN,NaN,COMP,COMP,False,-1,0
378,1351728,"0,144,191,281",uVar6,uint32,register,xmm1_db,4644,BUILTIN,uint32,NaN,NaN,NaN,NaN,NaN,COMP,COMP,False,-1,0
379,1351728,"505,548,865,908,1225,1268",local_378,uint64,stack,NaN,-888,BUILTIN,uint64,NaN,NaN,NaN,NaN,NaN,COMP,COMP,False,-1,0
380,1351728,"555,915,1275",local_370,uint64,stack,NaN,-880,BUILTIN,uint64,NaN,NaN,NaN,NaN,NaN,COMP,COMP,False,-1,0
381,1351728,"576,936,1296",local_368,uint64,stack,NaN,-872,BUILTIN,uint64,NaN,NaN,NaN,NaN,NaN,COMP,COMP,False,-1,0
382,1351728,"583,943,1303",local_360,uint64,stack,NaN,-864,BUILTIN,uint64,NaN,NaN,NaN,NaN,NaN,COMP,COMP,False,-1,0
383,1351728,"604,964,1324",local_358,uint64,stack,NaN,-856,BUILTIN,uint64,local_358,r_sheet*,stack,NaN,-856.0,POINTER,"PTR,STRUCT",False,31,0
384,1351728,"611,971,1331",local_350,uint64,stack,NaN,-848,BUILTIN,uint64,local_350,uint64,stack,NaN,-848.0,BUILTIN,uint64,False,-1,0
385,1351728,"632,992,1352",local_348,uint64,stack,NaN,-840,BUILTIN,uint64,local_348,uint64,stack,NaN,-840.0,BUILTIN,uint64,False,-1,0
386,1351728,"639,999,1359",local_340,uint64,stack,NaN,-832,BUILTIN,uint64,local_340,uint64,stack,NaN,-832.0,BUILTIN,uint64,False,-1,0
387,1351728,"660,1020,1380",local_338,uint64,stack,NaN,-824,BUILTIN,uint64,local_338,uint64,stack,NaN,-824.0,BUILTIN,uint64,False,-1,0
388,1351728,"667,1027,1387",local_330,uint64,stack,NaN,-816,BUILTIN,uint64,local_330,uint64,stack,NaN,-816.0,BUILTIN,uint64,False,-1,0
389,1351728,"688,1048,1408",local_328,uint64,stack,NaN,-808,BUILTIN,uint64,NaN,NaN,NaN,NaN,NaN,COMP,COMP,False,-1,0
390,1351728,"695,1055,1415",local_320,uint64,stack,NaN,-800,BUILTIN,uint64,NaN,NaN,NaN,NaN,NaN,COMP,COMP,False,-1,0
391,1351728,"828,1188,1548",local_318,uint64,stack,NaN,-792,BUILTIN,uint64,local_318,uint64,stack,NaN,-792.0,BUILTIN,uint64,False,-1,0
392,1351728,"723,1083,1443",local_310,uint64,stack,NaN,-784,BUILTIN,uint64,NaN,NaN,NaN,NaN,NaN,COMP,COMP,False,-1,0
393,1351728,"744,1104,1464",local_308,uint64,stack,NaN,-776,BUILTIN,uint64,NaN,NaN,NaN,NaN,NaN,COMP,COMP,False,-1,0
394,1351728,"751,1111,1471",local_300,uint64,stack,NaN,-768,BUILTIN,uint64,NaN,NaN,NaN,NaN,NaN,COMP,COMP,False,-1,0
395,1351728,"772,1132,1492",local_2f8,uint64,stack,NaN,-760,BUILTIN,uint64,NaN,NaN,NaN,NaN,NaN,COMP,COMP,False,-1,0
396,1351728,"779,1139,1499",local_2f0,uint64,stack,NaN,-752,BUILTIN,uint64,NaN,NaN,NaN,NaN,NaN,COMP,COMP,False,-1,0
397,1351728,"800,1160,1520",local_2e8,uint64,stack,NaN,-744,BUILTIN,uint64,NaN,NaN,NaN,NaN,NaN,COMP,COMP,False,-1,0
398,1351728,"807,1167,1527",local_2e0,uint64,stack,NaN,-736,BUILTIN,uint64,NaN,NaN,NaN,NaN,NaN,COMP,COMP,False,-1,0
399,1351728,"821,1181,1541",local_2d8,uint64,stack,NaN,-728,BUILTIN,uint64,NaN,NaN,NaN,NaN,NaN,COMP,COMP,False,-1,0
400,1351728,30,local_2c0,uint32,stack,NaN,-704,BUILTIN,uint32,width,int32,stack,NaN,-704.0,BUILTIN,int32,True,-1,0
401,1351728,40,local_2bc,uint32,stack,NaN,-700,BUILTIN,uint32,height,int32,stack,NaN,-700.0,BUILTIN,int32,True,-1,0
402,1351728,"1572,1601",local_2b8,uint64,stack,NaN,-696,BUILTIN,uint64,sword_swoosh,r_anim*,stack,NaN,-696.0,POINTER,"PTR,STRUCT",True,34,0
403,1351728,"58,121,179,477,519,879,1239",local_2b0,float,stack,NaN,-688,BUILTIN,float,NaN,NaN,NaN,NaN,NaN,COMP,COMP,False,-1,0
404,1351728,"74,207,271",local_2ac,float,stack,NaN,-684,BUILTIN,float,NaN,NaN,NaN,NaN,NaN,COMP,COMP,False,-1,0
405,1351728,"90,114",local_2a8,uint32,stack,NaN,-680,BUILTIN,uint32,NaN,NaN,NaN,NaN,NaN,COMP,COMP,False,-1,0
406,1351728,106,local_2a4,uint32,stack,NaN,-676,BUILTIN,uint32,NaN,NaN,NaN,NaN,NaN,COMP,COMP,False,-1,0
407,1351728,"179,258",local_2a0,float,stack,NaN,-672,BUILTIN,float,NaN,NaN,NaN,NaN,NaN,COMP,COMP,False,-1,0
408,1351728,207,local_29c,float,stack,NaN,-668,BUILTIN,float,NaN,NaN,NaN,NaN,NaN,COMP,COMP,False,-1,0
409,1351728,"227,251",local_298,uint32,stack,NaN,-664,BUILTIN,uint32,NaN,NaN,NaN,NaN,NaN,COMP,COMP,False,-1,0
410,1351728,243,local_294,uint32,stack,NaN,-660,BUILTIN,uint32,NaN,NaN,NaN,NaN,NaN,COMP,COMP,False,-1,0
411,1351728,304,local_290,uint32,stack,NaN,-656,BUILTIN,uint32,NaN,NaN,NaN,NaN,NaN,COMP,COMP,False,-1,0
412,1351728,316,local_28c,uint32,stack,NaN,-652,BUILTIN,uint32,NaN,NaN,NaN,NaN,NaN,COMP,COMP,False,-1,0
413,1351728,332,local_288,uint32,stack,NaN,-648,BUILTIN,uint32,NaN,NaN,NaN,NaN,NaN,COMP,COMP,False,-1,0
414,1351728,348,local_284,uint32,stack,NaN,-644,BUILTIN,uint32,NaN,NaN,NaN,NaN,NaN,COMP,COMP,False,-1,0
415,1351728,"364,512,872,1232",local_280,uint32,stack,NaN,-640,BUILTIN,uint32,NaN,NaN,NaN,NaN,NaN,COMP,COMP,False,-1,0
416,1351728,380,local_27c,uint32,stack,NaN,-636,BUILTIN,uint32,NaN,NaN,NaN,NaN,NaN,COMP,COMP,False,-1,0
417,1351728,"134,425",local_278,uint64,stack,NaN,-632,BUILTIN,uint64,NaN,NaN,NaN,NaN,NaN,COMP,COMP,False,-1,0
418,1351728,"144,432",local_270,uint64,stack,NaN,-624,BUILTIN,uint64,NaN,NaN,NaN,NaN,NaN,COMP,COMP,False,-1,0

In [4]:
raw_debug[raw_debug.FunctionStart==addr]

,FunctionStart,Name,Signature,Type,LocType,LocRegName,LocOffset,TypeCategory,TypeSeq
411,1351728,lVar1,"15,1739",int64,unique,NaN,49792,BUILTIN,int64
412,1351728,afVar2,"144,144,494",float[2],unique,NaN,268435571,ARRAY,"ARR,float"
413,1351728,lVar3,"400,408,408,408",int64,register,rcx,8,BUILTIN,int64
414,1351728,ppVar4,"405,408,408,408",player_t*,register,rdi,56,POINTER,"PTR,STRUCT"
415,1351728,in_FS_OFFSET,"15,1739",int64,register,fs_offset,272,BUILTIN,int64
416,1351728,bVar5,"4,408",uchar,register,df,522,BUILTIN,uchar
417,1351728,extraout_XMM0_Qa,494,float[2],register,xmm0_qa,4608,ARRAY,"ARR,float"
418,1351728,extraout_XMM0_Qa_00,494,float[2],register,xmm0_qa,4608,ARRAY,"ARR,float"
419,1351728,in_XMM1_Da,144,uint32,register,xmm1_da,4640,BUILTIN,uint32
420,1351728,fVar6,"271,281",float,register,xmm1_da,4640,BUILTIN,float
421,1351728,in_XMM1_Db,144,uint32,register,xmm1_db,4644,BUILTIN,uint32
422,1351728,uVar7,"191,281",uint32,register,xmm1_db,4644,BUILTIN,uint32
423,1351728,local_378,"505,548,548,555,555,576,576,583,583,865,908,90...",uchar[32],stack,NaN,-888,ARRAY,"ARR,uchar"
424,1351728,local_358,"604,964,1324",r_sheet*,stack,NaN,-856,POINTER,"PTR,STRUCT"
425,1351728,local_350,"611,971,1331",uint64,stack,NaN,-848,BUILTIN,uint64
426,1351728,local_348,"632,992,1352",uint64,stack,NaN,-840,BUILTIN,uint64
427,1351728,local_340,"639,999,1359",uint64,stack,NaN,-832,BUILTIN,uint64
428,1351728,local_338,"660,1020,1380",uint64,stack,NaN,-824,BUILTIN,uint64
429,1351728,local_330,"667,1027,1387",uint64,stack,NaN,-816,BUILTIN,uint64
430,1351728,local_328,"688,688,1048,1048,1408,1408",uint64,stack,NaN,-808,BUILTIN,uint64
431,1351728,local_320,"695,695,1055,1055,1415,1415",uint64,stack,NaN,-800,BUILTIN,uint64
432,1351728,local_318,"828,1188,1548",uint64,stack,NaN,-792,BUILTIN,uint64
433,1351728,local_310,"723,723,1083,1083,1443,1443",uint64,stack,NaN,-784,BUILTIN,uint64
434,1351728,local_308,"744,744,1104,1104,1464,1464",uint64,stack,NaN,-776,BUILTIN,uint64
435,1351728,local_300,"751,751,1111,1111,1471,1471",uint64,stack,NaN,-768,BUILTIN,uint64
436,1351728,local_2f8,"772,772,1132,1132,1492,1492",uint64,stack,NaN,-760,BUILTIN,uint64
437,1351728,local_2f0,"779,779,1139,1139,1499,1499",uint64,stack,NaN,-752,BUILTIN,uint64
438,1351728,local_2e8,"800,800,1160,1160,1520,1520",uint64,stack,NaN,-744,BUILTIN,uint64
439,1351728,local_2e0,"807,807,1167,1167,1527,1527",uint64,stack,NaN,-736,BUILTIN,uint64
440,1351728,local_2d8,"821,821,1181,1181,1541,1541",uint64,stack,NaN,-728,BUILTIN,uint64
441,1351728,width,30,int32,stack,NaN,-704,BUILTIN,int32
442,1351728,height,40,int32,stack,NaN,-700,BUILTIN,int32
443,1351728,sword_swoosh,"1572,1601",r_anim*,stack,NaN,-696,POINTER,"PTR,STRUCT"
444,1351728,player_pos,"58,74,121,179,207,271,477,519,879,1239",float[2],stack,NaN,-688,ARRAY,"ARR,float"
445,1351728,player_halfsize,"90,106,114",float[2],stack,NaN,-680,ARRAY,"ARR,float"
446,1351728,sword_pos,"179,207,258",float[2],stack,NaN,-672,ARRAY,"ARR,float"
447,1351728,sword_halfsize,"227,243,251",float[2],stack,NaN,-664,ARRAY,"ARR,float"
448,1351728,zero,NaN,float[2],stack,NaN,-656,ARRAY,"ARR,float"
449,1351728,halfsize,NaN,float[2],stack,NaN,-648,ARRAY,"ARR,float"
450,1351728,sprite_size,"364,380,512,872,1232",float[2],stack,NaN,-640,ARRAY,"ARR,float"
451,1351728,player_col,NaN,c_aabb,stack,NaN,-632,STRUCT,STRUCT
452,1351728,sword_col,NaN,c_aabb,stack,NaN,-616,STRUCT,STRUCT

In [5]:
raw_strip[raw_strip.FunctionStart==addr]

,FunctionStart,Name,Signature,Type,LocType,LocRegName,LocOffset,TypeCategory,TypeSeq
391,1351728,lVar1,"400,408,408,408",int64,register,rcx,8,BUILTIN,int64
392,1351728,puVar2,"405,408,408,408",uint64*,register,rdi,56,POINTER,"PTR,uint64"
393,1351728,in_FS_OFFSET,"15,1739",int64,register,fs_offset,272,BUILTIN,int64
394,1351728,bVar3,"4,408",uchar,register,df,522,BUILTIN,uchar
395,1351728,fVar4,"271,281",float,register,xmm1_da,4640,BUILTIN,float
396,1351728,uVar5,"0,144",uint32,register,xmm1_db,4644,BUILTIN,uint32
397,1351728,uVar6,"0,144,191,281",uint32,register,xmm1_db,4644,BUILTIN,uint32
398,1351728,local_378,"505,548,865,908,1225,1268",uint64,stack,NaN,-888,BUILTIN,uint64
399,1351728,local_370,"555,915,1275",uint64,stack,NaN,-880,BUILTIN,uint64
400,1351728,local_368,"576,936,1296",uint64,stack,NaN,-872,BUILTIN,uint64
401,1351728,local_360,"583,943,1303",uint64,stack,NaN,-864,BUILTIN,uint64
402,1351728,local_358,"604,964,1324",uint64,stack,NaN,-856,BUILTIN,uint64
403,1351728,local_350,"611,971,1331",uint64,stack,NaN,-848,BUILTIN,uint64
404,1351728,local_348,"632,992,1352",uint64,stack,NaN,-840,BUILTIN,uint64
405,1351728,local_340,"639,999,1359",uint64,stack,NaN,-832,BUILTIN,uint64
406,1351728,local_338,"660,1020,1380",uint64,stack,NaN,-824,BUILTIN,uint64
407,1351728,local_330,"667,1027,1387",uint64,stack,NaN,-816,BUILTIN,uint64
408,1351728,local_328,"688,1048,1408",uint64,stack,NaN,-808,BUILTIN,uint64
409,1351728,local_320,"695,1055,1415",uint64,stack,NaN,-800,BUILTIN,uint64
410,1351728,local_318,"828,1188,1548",uint64,stack,NaN,-792,BUILTIN,uint64
411,1351728,local_310,"723,1083,1443",uint64,stack,NaN,-784,BUILTIN,uint64
412,1351728,local_308,"744,1104,1464",uint64,stack,NaN,-776,BUILTIN,uint64
413,1351728,local_300,"751,1111,1471",uint64,stack,NaN,-768,BUILTIN,uint64
414,1351728,local_2f8,"772,1132,1492",uint64,stack,NaN,-760,BUILTIN,uint64
415,1351728,local_2f0,"779,1139,1499",uint64,stack,NaN,-752,BUILTIN,uint64
416,1351728,local_2e8,"800,1160,1520",uint64,stack,NaN,-744,BUILTIN,uint64
417,1351728,local_2e0,"807,1167,1527",uint64,stack,NaN,-736,BUILTIN,uint64
418,1351728,local_2d8,"821,1181,1541",uint64,stack,NaN,-728,BUILTIN,uint64
419,1351728,local_2c0,30,uint32,stack,NaN,-704,BUILTIN,uint32
420,1351728,local_2bc,40,uint32,stack,NaN,-700,BUILTIN,uint32
421,1351728,local_2b8,"1572,1601",uint64,stack,NaN,-696,BUILTIN,uint64
422,1351728,local_2b0,"58,121,179,477,519,879,1239",float,stack,NaN,-688,BUILTIN,float
423,1351728,local_2ac,"74,207,271",float,stack,NaN,-684,BUILTIN,float
424,1351728,local_2a8,"90,114",uint32,stack,NaN,-680,BUILTIN,uint32
425,1351728,local_2a4,106,uint32,stack,NaN,-676,BUILTIN,uint32
426,1351728,local_2a0,"179,258",float,stack,NaN,-672,BUILTIN,float
427,1351728,local_29c,207,float,stack,NaN,-668,BUILTIN,float
428,1351728,local_298,"227,251",uint32,stack,NaN,-664,BUILTIN,uint32
429,1351728,local_294,243,uint32,stack,NaN,-660,BUILTIN,uint32
430,1351728,local_290,304,uint32,stack,NaN,-656,BUILTIN,uint32
431,1351728,local_28c,316,uint32,stack,NaN,-652,BUILTIN,uint32
432,1351728,local_288,332,uint32,stack,NaN,-648,BUILTIN,uint32
433,1351728,local_284,348,uint32,stack,NaN,-644,BUILTIN,uint32
434,1351728,local_280,"364,512,872,1232",uint32,stack,NaN,-640,BUILTIN,uint32
435,1351728,local_27c,380,uint32,stack,NaN,-636,BUILTIN,uint32
436,1351728,local_278,"134,425",uint64,stack,NaN,-632,BUILTIN,uint64
437,1351728,local_270,"144,432",uint64,stack,NaN,-624,BUILTIN,uint64
438,1351728,local_268,494,uint64,stack,NaN,-616,BUILTIN,uint64
439,1351728,local_260,494,uint64,stack,NaN,-608,BUILTIN,uint64
440,1351728,local_10,"15,1739",int64,stack,NaN,-16,BUILTIN,int64

In [6]:
raw_dwarf[raw_dwarf.FunctionStart==addr]

,Name,Type,LocType,LocRegName,LocOffset,FunctionStart,FunctionName,TypeCategory,TypeSeq
104,width,int32,UndefinedLoc,NaN,NaN,1351728,init_game,BUILTIN,int32
105,height,int32,UndefinedLoc,NaN,NaN,1351728,init_game,BUILTIN,int32
106,player_pos,float[2],UndefinedLoc,NaN,NaN,1351728,init_game,ARRAY,"ARR,float"
107,player_halfsize,float[2],UndefinedLoc,NaN,NaN,1351728,init_game,ARRAY,"ARR,float"
108,player_col,c_aabb,UndefinedLoc,NaN,NaN,1351728,init_game,STRUCT,STRUCT
109,sword_pos,float[2],UndefinedLoc,NaN,NaN,1351728,init_game,ARRAY,"ARR,float"
110,sword_halfsize,float[2],UndefinedLoc,NaN,NaN,1351728,init_game,ARRAY,"ARR,float"
111,sword_col,c_aabb,UndefinedLoc,NaN,NaN,1351728,init_game,STRUCT,STRUCT
112,zero,float[2],UndefinedLoc,NaN,NaN,1351728,init_game,ARRAY,"ARR,float"
113,halfsize,float[2],UndefinedLoc,NaN,NaN,1351728,init_game,ARRAY,"ARR,float"
114,sprite_size,float[2],UndefinedLoc,NaN,NaN,1351728,init_game,ARRAY,"ARR,float"
115,sword_swoosh,r_anim*,UndefinedLoc,NaN,NaN,1351728,init_game,POINTER,"PTR,STRUCT"

# Export DataTypeArchive
Ok, try this REALLY QUICK!
1. **I need this to be able to try out/investigate the member offset dataset!!**
2. If I can hand Dylan the `sword_swoosh` local from `init_game` that is a great test case

In [7]:
import pyhidra
pyhidra.start()

In [8]:
!ls ~/ghidra_projects

aarch64test.gpr  astera3.gpr  astera.gpr   astera.lock~
aarch64test.rep  astera3.rep  astera.lock  astera.rep

In [9]:
import typing
if typing.TYPE_CHECKING:
    import ghidra
    from ghidra.ghidra_builtins import *

from ghidralib.datatypes import to_varlib_dtype

# to_varlib_dtype()
import ghidra
from ghidra.base.project import GhidraProject

gproj = GhidraProject.openProject(Path.home()/'ghidra_projects', 'astera', False)

In [10]:
list(list(gproj.getRootFolder().getFolders())[0].getFiles())
prog = gproj.openProgram('/run1.gcc-O0.astera', '0.fighter.debug', True)

In [11]:
dtmgr = prog.getDataTypeManager()
s = dtmgr.getAllStructures().next()

In [12]:
stype = to_varlib_dtype(s, s.getLength())
stype.sid

# len([to_varlib_dtype(s, s.getLength()) for s in dtmgr.getAllStructures()])
[to_varlib_dtype(s, s.getLength()).name for s in dtmgr.getAllStructures()][:10]

['Elf64_Ehdr',
 'Elf64_Phdr',
 'Elf64_Shdr',
 'Elf64_Dyn',
 'Elf64_Sym',
 'Elf64_Rela',
 'NoteAbiTag',
 'NoteGnuProperty_4',
 'NoteGnuPropertyElement_4',
 '_IO_FILE']

In [13]:
from varlib.datatype import StructField

comp = list(s.getComponents())[0]
comp.getDataType()
comp.getOffset()
comp.getFieldName()
comp.getComment()
comp.getDefaultFieldName()
comp.getKey()
comp.getLength()
comp.getDataType().getLength()
comp.getOrdinal()
comp.getParent()
comp.getEndOffset()

f = StructField(to_varlib_dtype(comp.getDataType(), comp.getLength()), comp.getFieldName())
f.name
print(f)
print(f.name)
type(comp)

uchar e_ident_magic_num
e_ident_magic_num

# Export Ghidra Data Type Archive
The code below needs to be moved to `ghidralib`

In [14]:
from varlib import StructDatabase
from varlib.datatype import StructType, UnionType, StructDefinition, UnionDefinition, StructLayout, UnionLayout, StructField

def get_field(dt_comp:ghidra.program.model.data.DataTypeComponent):
    return StructField(to_varlib_dtype(dt_comp.getDataType(), dt_comp.getLength()), dt_comp.getFieldName())

def get_struct_layout(stype:ghidra.program.model.data.Structure) -> StructLayout:
    return StructLayout({x.getOffset(): get_field(x) for x in stype.getComponents()})

def get_struct_definition(stype:ghidra.program.model.data.Structure) -> StructDefinition:
    return StructDefinition(stype.name, get_struct_layout(stype))

def get_union_layout(utype:ghidra.program.model.data.Union) -> UnionLayout:
    return UnionLayout([get_field(x) for x in utype.getComponents()])

def get_union_definition(utype:ghidra.program.model.data.Union) -> UnionDefinition:
    return UnionDefinition(utype.name, get_union_layout(utype))

# Ghidra already has unique ids - just construct structs/unions_by_id manually
sdb = StructDatabase()

from tqdm import tqdm
# from tqdm.auto import tqdm
# for x in tqdm(iterator, total=total):
for ghidra_type in tqdm(dtmgr.getAllComposites(), total=len(list(dtmgr.getAllComposites()))):
    dtype = to_varlib_dtype(ghidra_type, ghidra_type.getLength())
    if isinstance(dtype, StructType):
        sdb.structs_by_id[dtype.sid] = get_struct_definition(ghidra_type)
    elif isinstance(dtype, UnionType):
        sdb.unions_by_id[dtype.sid] = get_union_definition(ghidra_type)
    else:
        raise Exception(f'Unhandled datatype {type(dtype)}: {dtype}')

100%|██████████| 406/406 [00:00<00:00, 922.36it/s]

In [15]:
k = list(sdb.structs_by_id.keys())[35]
print(sdb.structs_by_id[k])

struct r_anim_viewer {
	0x0: r_anim* anim
	0x8: double time
	0x10: double rate
	0x18: uint32 curr
	0x1c: uint32 count
	0x20: uchar state
	0x21: uchar pstate
	0x22: char loop
}

In [16]:
sdb.to_json('astera.debug.sdb')

In [17]:
!ls -Ahl

total 2.2M
-rw-rw-r-- 1 cls0027 cls0027 1.1M Feb  2 19:19 astera.debug.sdb
-rw-rw-r-- 1 cls0027 cls0027 1.1M Feb  1 19:00 astera.sdb
-rw-rw-r-- 1 cls0027 cls0027 3.9K Feb  1 10:47 ast_updates.ipynb
-rw-rw-r-- 1 cls0027 cls0027 111K Feb  1 20:14 dylan_sandbox.ipynb
drwxrwxr-x 8 cls0027 cls0027 4.0K Feb  2 19:03 .git
-rw-rw-r-- 1 cls0027 cls0027   34 Feb  1 19:11 .gitignore
-rw-rw-r-- 1 cls0027 cls0027   90 May 15  2023 pyproject.toml
-rw-rw-r-- 1 cls0027 cls0027   72 Aug 21 19:57 README.md
-rw-rw-r-- 1 cls0027 cls0027  524 Jan 30 20:39 setup.cfg
drwxrwxr-x 7 cls0027 cls0027 4.0K Jan 30 09:06 src

In [18]:
sdb2 = sdb.from_json('astera.sdb')

In [19]:
sid = sdb2.sids_by_name['r_anim'][0]
sdb2.structs_by_id[sid]

struct r_anim {
	0x0: uint32 id
	0x8: uint32* frames
	0x10: double* lengths
	0x18: uint32 count
	0x20: double rate
	0x28: r_sheet* sheet
	0x30: char loop
}

In [20]:
locals_df[locals_df.FunctionStart==addr]

,FunctionStart,Signature,Name_Strip,Type_Strip,LocType_Strip,LocRegName_Strip,LocOffset_Strip,TypeCategory_Strip,TypeSeq_Strip,Name_Debug,Type_Debug,LocType_Debug,LocRegName_Debug,LocOffset_Debug,TypeCategory_Debug,TypeSeq_Debug,HasDWARF,LeafSID,BinaryId
373,1351728,"400,408,408,408",lVar1,int64,register,rcx,8,BUILTIN,int64,lVar3,int64,register,rcx,8.0,BUILTIN,int64,False,-1,0
374,1351728,"405,408,408,408",puVar2,uint64*,register,rdi,56,POINTER,"PTR,uint64",ppVar4,player_t*,register,rdi,56.0,POINTER,"PTR,STRUCT",False,58,0
375,1351728,"4,408",bVar3,uchar,register,df,522,BUILTIN,uchar,bVar5,uchar,register,df,522.0,BUILTIN,uchar,False,-1,0
376,1351728,"271,281",fVar4,float,register,xmm1_da,4640,BUILTIN,float,fVar6,float,register,xmm1_da,4640.0,BUILTIN,float,False,-1,0
377,1351728,"0,144",uVar5,uint32,register,xmm1_db,4644,BUILTIN,uint32,NaN,NaN,NaN,NaN,NaN,COMP,COMP,False,-1,0
378,1351728,"0,144,191,281",uVar6,uint32,register,xmm1_db,4644,BUILTIN,uint32,NaN,NaN,NaN,NaN,NaN,COMP,COMP,False,-1,0
379,1351728,"505,548,865,908,1225,1268",local_378,uint64,stack,NaN,-888,BUILTIN,uint64,NaN,NaN,NaN,NaN,NaN,COMP,COMP,False,-1,0
380,1351728,"555,915,1275",local_370,uint64,stack,NaN,-880,BUILTIN,uint64,NaN,NaN,NaN,NaN,NaN,COMP,COMP,False,-1,0
381,1351728,"576,936,1296",local_368,uint64,stack,NaN,-872,BUILTIN,uint64,NaN,NaN,NaN,NaN,NaN,COMP,COMP,False,-1,0
382,1351728,"583,943,1303",local_360,uint64,stack,NaN,-864,BUILTIN,uint64,NaN,NaN,NaN,NaN,NaN,COMP,COMP,False,-1,0
383,1351728,"604,964,1324",local_358,uint64,stack,NaN,-856,BUILTIN,uint64,local_358,r_sheet*,stack,NaN,-856.0,POINTER,"PTR,STRUCT",False,31,0
384,1351728,"611,971,1331",local_350,uint64,stack,NaN,-848,BUILTIN,uint64,local_350,uint64,stack,NaN,-848.0,BUILTIN,uint64,False,-1,0
385,1351728,"632,992,1352",local_348,uint64,stack,NaN,-840,BUILTIN,uint64,local_348,uint64,stack,NaN,-840.0,BUILTIN,uint64,False,-1,0
386,1351728,"639,999,1359",local_340,uint64,stack,NaN,-832,BUILTIN,uint64,local_340,uint64,stack,NaN,-832.0,BUILTIN,uint64,False,-1,0
387,1351728,"660,1020,1380",local_338,uint64,stack,NaN,-824,BUILTIN,uint64,local_338,uint64,stack,NaN,-824.0,BUILTIN,uint64,False,-1,0
388,1351728,"667,1027,1387",local_330,uint64,stack,NaN,-816,BUILTIN,uint64,local_330,uint64,stack,NaN,-816.0,BUILTIN,uint64,False,-1,0
389,1351728,"688,1048,1408",local_328,uint64,stack,NaN,-808,BUILTIN,uint64,NaN,NaN,NaN,NaN,NaN,COMP,COMP,False,-1,0
390,1351728,"695,1055,1415",local_320,uint64,stack,NaN,-800,BUILTIN,uint64,NaN,NaN,NaN,NaN,NaN,COMP,COMP,False,-1,0
391,1351728,"828,1188,1548",local_318,uint64,stack,NaN,-792,BUILTIN,uint64,local_318,uint64,stack,NaN,-792.0,BUILTIN,uint64,False,-1,0
392,1351728,"723,1083,1443",local_310,uint64,stack,NaN,-784,BUILTIN,uint64,NaN,NaN,NaN,NaN,NaN,COMP,COMP,False,-1,0
393,1351728,"744,1104,1464",local_308,uint64,stack,NaN,-776,BUILTIN,uint64,NaN,NaN,NaN,NaN,NaN,COMP,COMP,False,-1,0
394,1351728,"751,1111,1471",local_300,uint64,stack,NaN,-768,BUILTIN,uint64,NaN,NaN,NaN,NaN,NaN,COMP,COMP,False,-1,0
395,1351728,"772,1132,1492",local_2f8,uint64,stack,NaN,-760,BUILTIN,uint64,NaN,NaN,NaN,NaN,NaN,COMP,COMP,False,-1,0
396,1351728,"779,1139,1499",local_2f0,uint64,stack,NaN,-752,BUILTIN,uint64,NaN,NaN,NaN,NaN,NaN,COMP,COMP,False,-1,0
397,1351728,"800,1160,1520",local_2e8,uint64,stack,NaN,-744,BUILTIN,uint64,NaN,NaN,NaN,NaN,NaN,COMP,COMP,False,-1,0
398,1351728,"807,1167,1527",local_2e0,uint64,stack,NaN,-736,BUILTIN,uint64,NaN,NaN,NaN,NaN,NaN,COMP,COMP,False,-1,0
399,1351728,"821,1181,1541",local_2d8,uint64,stack,NaN,-728,BUILTIN,uint64,NaN,NaN,NaN,NaN,NaN,COMP,COMP,False,-1,0
400,1351728,30,local_2c0,uint32,stack,NaN,-704,BUILTIN,uint32,width,int32,stack,NaN,-704.0,BUILTIN,int32,True,-1,0
401,1351728,40,local_2bc,uint32,stack,NaN,-700,BUILTIN,uint32,height,int32,stack,NaN,-700.0,BUILTIN,int32,True,-1,0
402,1351728,"1572,1601",local_2b8,uint64,stack,NaN,-696,BUILTIN,uint64,sword_swoosh,r_anim*,stack,NaN,-696.0,POINTER,"PTR,STRUCT",True,34,0
403,1351728,"58,121,179,477,519,879,1239",local_2b0,float,stack,NaN,-688,BUILTIN,float,NaN,NaN,NaN,NaN,NaN,COMP,COMP,False,-1,0
404,1351728,"74,207,271",local_2ac,float,stack,NaN,-684,BUILTIN,float,NaN,NaN,NaN,NaN,NaN,COMP,COMP,False,-1,0
405,1351728,"90,114",local_2a8,uint32,stack,NaN,-680,BUILTIN,uint32,NaN,NaN,NaN,NaN,NaN,COMP,COMP,False,-1,0
406,1351728,106,local_2a4,uint32,stack,NaN,-676,BUILTIN,uint32,NaN,NaN,NaN,NaN,NaN,COMP,COMP,False,-1,0
407,1351728,"179,258",local_2a0,float,stack,NaN,-672,BUILTIN,float,NaN,NaN,NaN,NaN,NaN,COMP,COMP,False,-1,0
408,1351728,207,local_29c,float,stack,NaN,-668,BUILTIN,float,NaN,NaN,NaN,NaN,NaN,COMP,COMP,False,-1,0
409,1351728,"227,251",local_298,uint32,stack,NaN,-664,BUILTIN,uint32,NaN,NaN,NaN,NaN,NaN,COMP,COMP,False,-1,0
410,1351728,243,local_294,uint32,stack,NaN,-660,BUILTIN,uint32,NaN,NaN,NaN,NaN,NaN,COMP,COMP,False,-1,0
411,1351728,304,local_290,uint32,stack,NaN,-656,BUILTIN,uint32,NaN,NaN,NaN,NaN,NaN,COMP,COMP,False,-1,0
412,1351728,316,local_28c,uint32,stack,NaN,-652,BUILTIN,uint32,NaN,NaN,NaN,NaN,NaN,COMP,COMP,False,-1,0
413,1351728,332,local_288,uint32,stack,NaN,-648,BUILTIN,uint32,NaN,NaN,NaN,NaN,NaN,COMP,COMP,False,-1,0
414,1351728,348,local_284,uint32,stack,NaN,-644,BUILTIN,uint32,NaN,NaN,NaN,NaN,NaN,COMP,COMP,False,-1,0
415,1351728,"364,512,872,1232",local_280,uint32,stack,NaN,-640,BUILTIN,uint32,NaN,NaN,NaN,NaN,NaN,COMP,COMP,False,-1,0
416,1351728,380,local_27c,uint32,stack,NaN,-636,BUILTIN,uint32,NaN,NaN,NaN,NaN,NaN,COMP,COMP,False,-1,0
417,1351728,"134,425",local_278,uint64,stack,NaN,-632,BUILTIN,uint64,NaN,NaN,NaN,NaN,NaN,COMP,COMP,False,-1,0
418,1351728,"144,432",local_270,uint64,stack,NaN,-624,BUILTIN,uint64,NaN,NaN,NaN,NaN,NaN,COMP,COMP,False,-1,0

In [24]:
# ghidra imports
from ghidra.program.model.listing import Program

# my stuff (astlib)
from varlib import datatype

###################################################################
# STUB CLASS/FUNCTIONS (aka what I need you to implement)
# -----------------------------------------------------------------
# This is a specific example of the general idea I'm looking for...lol
#
# What I mean is, we can totally tweak the API - this is just my best
# guess at a concrete example of what I need
###################################################################

class GhidraRetyper:
    def __init__(self, program:Program, reference_db:StructDatabase) -> None:
        # NOTE: I think this is all the Ghidra context you'll need
        # to access database things but add more if you need to
        self.program = program

        # right now the db I'm handing you has everything, but
        # the only guarantee is that it has definitions for all of
        # the structure/union types I actually ask you to apply
        # (and their dependencies) so it may be a subset of
        # Ghidra's full data type archive in general
        self.reference_db = reference_db

    def define_all_reference_types(self, overwrite_existing:bool=False):

        # this is where you may need to perform a topological sort
        # or w/e to handle dependencies (structs within structs)
        # Jacob did this recently...may be good to ask him about it
        print(f'DYLAN TODO: make sure this works for nested structure/union types...')

        # Caleb's naive implementation:
        for sid, stype in self.reference_db.structs_by_id:
            self.define_struct_type(stype, overwrite_existing)

        for uid, utype in self.reference_db.unions_by_id:
            self.define_union_type(utype, overwrite_existing)

    def define_struct_type(self, stype:datatype.StructType, overwrite_existing:bool=False):
        # define the structure using its given name and layout
        # --> IGNORE THE SID (stype.sid). Ghidra will assign its own ID and I will
        #     probably re-export the data type archive and remap the ids outside of this
        #     Regardless, I won't assume the sids are still valid once this completes.
        #     I will only assume the structure with the given name is defined in the database

        # also...if Ghidra wants you to pick a path for the data types (that show up in
        # the data type manager tree on the left), we can just use some hardcoded path
        # for all type we define for now (e.g. "/GhidraRetyper")

        # if overwrite_existing then blow away an existing struct with the same name
        print(f'DYLAN TODO: define structure type {stype.name} in Ghidra')

    def define_union_type(self, utype:datatype.UnionType, overwrite_existing:bool=False):
        # same as above, but unions...
        print(f'DYLAN TODO: define union type {utype.name} in Ghidra')

    def set_localvar_type(self, func_addr:int, local_name:str, dtype:datatype.DataType):
        print(f'DYLAN TODO: set decompiler local {local_name} in {func_addr:#x} to type {dtype}')

    def set_globalvar_type(self, global_name:int, global_type:datatype.DataType):
        # do this last: I don't have data for globals right now and we may not need them
        # ...but, while you're doing the others if this is straightforward you can add
        # support for globals too
        pass

    def set_param_type(self, func_addr:int, param_name:str, dtype:datatype.DataType):
        print(f'DYLAN TODO: set decompiler parameter {param_name} in {func_addr:#x} to type {dtype}')

    def set_return_type(self, func_addr:int, dtype:datatype.DataType):
        print(f'DYLAN TODO: set decompiler return type for function {func_addr:#x} to type {dtype}')

###################################################################
# DRIVER CODE
# -----------------------------------------------------------------
# My test cases and a good example of how I will use your class
###################################################################


# --------------------------------
# CALEB TODO:

# save/restore data types via TypeJson_Debug <<<

# --------------------------------
# STRUCT - include sid
# PTR - pointer, keep going...
# uint64, uchar, etc. - convert from standard name...

retyper = GhidraRetyper(prog, sdb2)
func_locals = locals_df[locals_df.FunctionStart==addr]
for i in range(len(func_locals)):
    x = func_locals.iloc[i]
    # retyper.set_localvar_type(addr, x.Name_Strip, x.Type_Debug)
    print(x.TypeSeq_Debug, x.LeafSID)

int64 -1
PTR,STRUCT 58
uchar -1
float -1
COMP -1
COMP -1
COMP -1
COMP -1
COMP -1
COMP -1
PTR,STRUCT 31
uint64 -1
uint64 -1
uint64 -1
uint64 -1
uint64 -1
COMP -1
COMP -1
uint64 -1
COMP -1
COMP -1
COMP -1
COMP -1
COMP -1
COMP -1
COMP -1
COMP -1
int32 -1
int32 -1
PTR,STRUCT 34
COMP -1
COMP -1
COMP -1
COMP -1
COMP -1
COMP -1
COMP -1
COMP -1
COMP -1
COMP -1
COMP -1
COMP -1
COMP -1
COMP -1
COMP -1
COMP -1